<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Create module') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('With this module you can build fast the module skeleton and start working on the cool stuff'); ?></p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url( 'moduler' ); ?>" target="_blank"><?php echo $this->translate('Create module') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Create form') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('With this module you can build fast a form with validation and table structure and start working on the cool stuff'); ?></p>
                <p><a class="btn btn-success pull-right" href="<?php //echo $this->url( 'form' ); ?>" target="_blank"><?php echo $this->translate('Create form') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Create table gateway') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('With this module you can build fast a table gateway and start working on the cool stuff'); ?></p>
                <p><a class="btn btn-success pull-right" href="<?php //echo $this->url( 'gateway' ); ?>" target="_blank"><?php echo $this->translate('Create table gateway') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
